### ISSUE TITLE
PageParser::new does not check the first four magic bytes

### ISSUE THREAD

**Issue by TonalidadeHidrica** [est31/ogg#13]
As long as I read the [code](https://github.com/RustAudio/ogg/blob/master/src/reading.rs#L184), the PageParser does not seem to check the first four bytes four valid `OggS` magic.   Is there some reason?

**Comment by est31** [comment]
See the documentation:

> Determining when one begins is your responsibility.

The magic is checked somewhere else in the code. I didn't want to duplicate it.

**Comment by TonalidadeHidrica** [comment]
Oops, sorry for not reading docs carefully...
