### ISSUE TITLE
PacketWriter::write_packet taking packet contents as Box<[u8]> is onerous

### ISSUE THREAD

**Issue by FrancisRussell** [est31/ogg#19]
`PacketWriter::write_packet` takes the packet contents as a Box<[u8]>. This is contrary to what would be expected which would be to take a reference to a slice. Since the Box is consumed, the library user is required to allocate a buffer for their packet each time around the loop.

**Comment by AlexTMjugador** [comment]
I've just looked into this, and changing the code so it takes a slice reference would require that reference to be valid for the lifetime of the `PacketWriter` struct, as packet writes for different logical bitstreams may be interleaved arbitrarily, and a page may contain several packets. That lifetime requirement would make this improvement less useful in practice, as I'd expect client code to call `write_packet` and then want to drop the packet data shortly afterwards, not keep it lying around in memory. I don't think using a smart pointer like `Cow` would help reducing allocations compared to the current `Box`, either.

Apart from somewhat degenerate use cases where packet contents are known beforehand, would such a change be welcome and useful for this crate?

**Comment by AlexTMjugador** [comment]
I've just been bold and submitted a PR to remove this boxing requirement anyway, as it is a trivial change, it may be useful in some use cases, and it feels like a nicer API design overall. Its implications are not so trivial, though.

**Comment by est31** [comment]
Fixed by #25
