### ISSUE TITLE
Are there any plans for a new release?

### ISSUE THREAD

**Issue by AlexTMjugador** [est31/ogg#35]
Hi!

I've just published [OptiVorbis](https://github.com/OptiVorbis/OptiVorbis), a Rust library and CLI application for lossless optimization of Ogg Vorbis files, which depends on this `ogg` crate. I've been developing it these months, so that explains my PRs to this repository ;)

In OptiVorbis, I've been using the latest commits of this repository via the Cargo's manifest [`[patch]` section](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#the-patch-section). My crate depends on the changes I've submitted in PRs to function as I want at this point. However, when trying to publish my crate on crates.io, I faced the reality that crates.io ignores dependency patches, so my library won't work.

I'd be interested in knowing if there is anything left to do for a new release, or if you have some timeline in mind. Thank you!

**Comment by est31** [comment]
Yeah I can make a new release later today, or tomorrow. Let's see.

**Comment by est31** [comment]
Done! 0910d8d57645eccc1a1400731fefef376859c661

**Comment by est31** [comment]
(Also, btw your project looks really amazing)

**Comment by AlexTMjugador** [comment]
Thank you for the prompt release, it's really appreciated!
