### ISSUE TITLE
Are there any plans for a new release (again)?

### ISSUE THREAD

**Issue by AlexTMjugador** [est31/ogg#40]
Hello!

After #38 was merged, I have found a use for it in my OptiVorbis project, which at the moment [patches the `ogg` dependency with a commit that includes these changes](https://github.com/OptiVorbis/OptiVorbis/blob/62e37d2b17bbec94e95db86af31333ad20388073/Cargo.toml#L21-L25). However, `crates.io` ignores Cargo dependency patches, which limits my ability to release there a new version of OptiVorbis with the features that depend on #38.

So again, I'm wondering if it would be possible to get a new `ogg` patch release with these changes, which I deem stable. Thanks in advance!

**Comment by est31** [comment]
thanks for the request! Yeah it would make sense to do a release.

**Comment by est31** [comment]
Done. da3c597c5e2966ee7df206dba298c229ecce3a01

**Comment by AlexTMjugador** [comment]
Awesome, thank you! :tada:
